old_version/pantry/health/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('pantry.health.views',
    url(r'^$', 'home', name='health_home'),
    url(r'^activity_log/$', 'activity_log_home', name='activity_log_home'),
    url(r'^activity_log/add/$', 'activity_log_add', name='activity_log_add'),
    url(r'^ajax_get_exercise/$', 'ajax_get_exercise'),
)

old_version/pantry/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
#from pantry import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^accounts/', include('pantry.accounts.urls')),
    url(r'^stocks/', include('pantry.stocks.urls')),
    url(r'^health/', include('pantry.health.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

pantry/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pantry.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^store/', include('store.urls')),
)

store/urls.py
from django.conf.urls import patterns, url
from store.views import *
from store.models import Product, Package, Stock

urlpatterns = patterns('store.views',
    url(r'^$', 'home', name='home'),

    url(r'^products/$', ProductList.as_view(), name='product-list'),
    url(r'^products/(?P<pk>\d+)/$', ProductDetail.as_view(), name='product-detail'),
    url(r'^products/new/$', product_update, name='product-add'),
    url(r'^products/update/(?P<pk>\d+)/$', product_update, name='product-update'),
    url(r'^products/search/barcode/$', ProductSearchBarcode.as_view(), name='product-search-barcode'),

    url(r'^products/lookup/$', ProductLookup.as_view(), name='product-lookup'),
#    url(r'^products/new_from_lookup/$', product_create_from_lookup, name='product-add-lookup'),

    url(r'^stocks/$', StockList.as_view(), name='stock-list'),
    url(r'^stocks/(?P<pk>\d+)/$', StockDetail.as_view(), name='stock-detail'),
    url(r'^stocks/new/$', StockCreate.as_view(), name='stock-add'),
    url(r'^stocks/update/(?P<pk>\d+)/$', StockUpdate.as_view(), name='stock-update'),
    url(r'^stocks/search/barcode/$', StockSearchBarcode.as_view(), name='stock-search-barcode'),
)

old_version/pantry/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    dob = models.DateField('date of birth', null=True, blank=True)
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)

    def get_age(self, date):
        return date.year - self.dob.year

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
post_save.connect(create_user_profile, sender=User)

old_version/pantry/health/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

def calc_bmi(w, h):
    return w / h ** 2

def calc_bmr(g, w, h, a):
    ''' Basal metabolic rate as calculated from Revised Harris-Benedict equation '''
    if g == 'M':
        return 13.397 * w + 479.9 * h - 5.677 * a + 88.362
    elif g == 'F':
        return 9.247 * w + 309.8 * h - 4.330 * a + 447.593
    else:
        raise Exception

class Exercise(models.Model):
    name = models.CharField(max_length=30)
    energy_distance = models.FloatField('Calories per kg per km', null=True, blank=True)
    energy_time = models.FloatField('Calories per kg per min', null=True, blank=True)
    energy_unit = models.FloatField('Calories per kg per unit', null=True, blank=True)
    aerobic = models.BooleanField()

class ActivityLog(models.Model):
    user = models.ForeignKey(User)
    date = models.DateField('activity Date', default=datetime.date.today)    
    description = models.CharField(max_length=30)    
    energy = models.FloatField(null=True, blank=True)
    fat = models.FloatField(null=True, blank=True)
    carb = models.FloatField(null=True, blank=True)
    protein = models.FloatField(null=True, blank=True)
    salt = models.FloatField(null=True, blank=True)

    @staticmethod
    def get_net_energy(user, date):
        bmr = HealthLog.calc_bmr(user, date)
        nonbmr = sum((a.energy for a in ActivityLog.objects.filter(date__exact=date).filter(user__pk=user.pk)))
        return nonbmr - bmr

class HealthLog(models.Model):
    user = models.ForeignKey(User)
    date = models.DateField('activity Date', default=datetime.date.today)    
    height = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    fat = models.FloatField("fat percentage", null=True, blank=True)
    muscle = models.FloatField("muscle percentage", null=True, blank=True)
    water = models.FloatField("water percentage", null=True, blank=True)

    @staticmethod
    def calc_weight(user, date):
        # Big stub
        return HealthLog.objects.filter(date__exact=date).filter(user__pk=user.pk).order_by('date')[0].weight

    @staticmethod    
    def calc_height(user, date):
        # Big stub
        return HealthLog.objects.filter(date__exact=date).filter(user__pk=user.pk).order_by('date')[0].height

    @staticmethod    
    def calc_bmi(user, date):
        return calc_bmi(HealthLog.calc_weight(user, date), HealthLog.calc_height(user, date))

    @staticmethod    
    def calc_bmr(user, date):
        return calc_bmr(user.userprofile.gender, HealthLog.calc_weight(user, date), HealthLog.calc_height(user, date), user.get_age(date))

old_version/pantry/stocks/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class Error(Exception):
    pass
class QuantityUnknown(Error):
    pass

class Ingredient(models.Model):
    name = models.CharField(max_length=20, primary_key=True)
    products = models.ManyToManyField('Product')

    def __unicode__(self):
        return self.name

class Recipe(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    ingredients = models.ManyToManyField(Ingredient)
    serves_min = models.IntegerField('Minimum number served', default=1)

    def __unicode__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    energy = models.FloatField('Energy per 100g (Cal)', null=True, blank=True)
    protein = models.FloatField('Protein %', null=True, blank=True)
    carb = models.FloatField('Carbohydrate %', null=True, blank=True)
    fat = models.FloatField('Fat %', null=True, blank=True)
    sodium = models.FloatField('Sodium %', null=True, blank=True)

    def __unicode__(self):
        return self.name

class Package(models.Model):
    product = models.ForeignKey(Product)
    barcode = models.CharField(max_length=15, null=True, blank=True)
    quantity = models.FloatField('quantity (g or ml)', null=True, blank=True)

    def __unicode__(self):
        return self.product.__unicode__() + ': ' + self.description

class Stock(models.Model):
    user = models.ForeignKey(User)
    package = models.ForeignKey(Package)
    fraction = models.FloatField(default=1.0, editable=False)
    use_date = models.DateField('use-by date', null=True, blank=True)

    def remove(self):
        self.fraction = 0.0
        self.save()

    def use_fraction(self, f):
        self.fraction -= f
        self.save()

    def use_fraction_current(self, f):
        self.use_fraction(f * self.fraction)

    def use_quantity(self, q):
        try:
            self.use_fraction(q / self.package.quantity)
        except TypeError:
            raise QuantityUnknown

    def get_quantity(self, q):
        try:
            return self.fraction * self.package.quantity
        except TypeError:
            raise QuantityUnknown

    def is_finished(self):
        return self.fraction <= 0.0

    def __unicode__(self):
        return self.package.__unicode__() + ' (%.0f%%)' % (100.0 * self.fraction)

def handle_stock_save(sender, instance, created, **kwargs):
    if created:
        instance.quantity = instance.package.quantity
        instance.save()
    if instance.is_finished():
        instance.delete()

post_save.connect(handle_stock_save, sender=Stock)

old_version/pantry/accounts/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse

class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))
    password = forms.CharField(max_length=20)

def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST) 
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            print(username, password)
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    messages.error(request, 'User account not active.')
                    return HttpResponseRedirect(reverse('login_page'))
            else:
                messages.error(request, 'Login failed!')
                return HttpResponseRedirect(reverse('login_page'))
    else:
        form = LoginForm()
    args = {'form': form}
    if 'next' not in request.GET:
        args['next'] = None
    else:
        args['next'] = request.GET['next']
    return render(request, 'accounts/login.html', args)

def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

old_version/pantry/health/views.py
import datetime
from django import forms
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, NoReverseMatch
from django.contrib.auth.models import User
from django.core import serializers
from pantry.health.models import HealthLog, ActivityLog, Exercise
from pantry.stocks.models import Product

def home(request):
    return HttpResponseRedirect(reverse('activity_log_add'))

class HealthLogForm(forms.ModelForm):
    class Meta:
        model = HealthLog

class ActivityLogForm(forms.Form):
    user = forms.ModelChoiceField(User.objects.all())
    date = forms.DateField(initial=datetime.date.today)
    description = forms.CharField(max_length=30)
    ACTIVITY_CHOICES = (('F', 'Food'), ('E', 'Exercise'))
    activity = forms.ChoiceField(ACTIVITY_CHOICES, initial='F')

    product = forms.ModelChoiceField(Product.objects.all(), required=False)
    product_quantity = forms.FloatField(required=False)
    
    exercise = forms.ModelChoiceField(Exercise.objects.all(), required=False)
    EXERCISE_MEASURE_CHOICES = (('T', 'Time'), ('D', 'Distance'), ('U', 'Units'), ('E', 'Energy'))
    exercise_measure = forms.ChoiceField(EXERCISE_MEASURE_CHOICES)
    exercise_quantity = forms.FloatField(required=False)

    energy = forms.FloatField(required=False)
    carb = forms.FloatField('carbohydrate', required=False)
    fat = forms.FloatField(required=False)
    protein = forms.FloatField(required=False)
    salt = forms.FloatField(required=False)

@login_required
def activity_log_add(request):
    if request.method == 'POST':
        form = ActivityLogForm(request.POST)
        if form.is_valid():
            a = ActivityLog(user=request.user, date=form.cleaned_data['date'], description=form.cleaned_data['description'], 
                            energy=form.cleaned_data['energy'], fat=form.cleaned_data['fat'], carb=form.cleaned_data['carb'],
                            protein=form.cleaned_data['protein'], salt=form.cleaned_data['salt'])
            a.save()
            return 
    else:
        form = ActivityLogForm()
    return render(request, 'health/activity_log_add.html', {
        'form': form,
        'products': Product.objects.all()
    })

def activity_log_home(request):
    return HttpResponseRedirect(reverse('activity_log_add'))

def ajax_get_exercise(request):
    if request.is_ajax() and request.method == 'GET':
        exercise = Exercise.objects.get(pk=request.GET['pk'])
        data = serializers.serialize('json', [exercise], ensure_ascii=False)
        return HttpResponse(data, 'application/javascript')
    return HttpResponse(status=400)    

pantry/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

old_version/pantry/templates/health/activity_log_add.html
<head>
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/myform.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript">
function change_activity_fields() {
    var act = $("#id_activity").val()
    if (act == "F") {
        $("#exf").hide()
        $("#foodf").show()
        $(".nutrient").show()
        var prod = $("#id_product").val()
        if (!prod) {
            $("#prodq").hide()
            $("#stats").show()
            $("#desc").show()
        } else {
            $("#prodq").show()
            $("#stats").hide()
        }
    } else if (act == "E") {
        $("#exf").show()
        $("#foodf").hide()
        $(".nutrient").hide()
        var ex = $("#id_exercise").val()
        if (!ex) {
            $("#exmeas").hide()
            $("#exq").hide()
            $("#stats").show()
            $("#desc").show()
        } else {
            $("#exmeas").show()
            $("#desc").hide()
            var exmeas = $("#id_exercise_measure").val()
            if (exmeas == "T" || exmeas == 'D' || exmeas =='U') {
                $("#exq").show()
                $("#stats").hide()
            } else if (exmeas == "E") {
                $("#exq").hide()
                $("#stats").show()
            }
        }
    } else {
        alert(value)
    }
}

$(document).ready(change_activity_fields)

$(document).ready(function() {
    $("#id_activity").change(change_activity_fields)
    $("#id_product").change(change_activity_fields)
    $("#id_exercise").change(change_activity_fields)
    $("#id_exercise_measure").change(change_activity_fields)
})
</script>
</head>

<body>
    <form action="/health/activity_log/add/" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>General</legend>
            <ol>
                <li>{{ form.user.label_tag }}{{ form.user }}</li>
                <li>{{ form.date.label_tag }}{{ form.date }}</li>
                <li>{{ form.activity.label_tag }}{{ form.activity }}</li>
            </ol>
        </fieldset>

        <fieldset id="foodf">
            <legend>Food</legend>
            <ol>
                <li id="prod">{{ form.product.label_tag }}{{ form.product }}</li>
                <li id="prodq">{{ form.product_quantity.label_tag }}{{ form.product_quantity }}</li>
            </ol>
        </fieldset>

        <fieldset id="exf">
            <legend>Exercise</legend>
            <ol>
                <li id="ex">{{ form.exercise.label_tag }}{{ form.exercise }}</li>
                <li id="exmeas">{{ form.exercise_measure.label_tag }}{{ form.exercise_measure }}</li>
                <li id="exq">{{ form.exercise_quantity.label_tag }}{{ form.exercise_quantity }}</li>    
            </ol>
        </fieldset>

        <fieldset id="stats">
            <legend>Detailed</legend>
            <ol>
                <li id="desc">{{ form.description.label_tag }}{{ form.description }}</li>
                <li id="energy">{{ form.energy.label_tag }}{{ form.energy }}</li>
                <li class="nutrient">{{ form.carb.label_tag }}{{ form.carb }}</li>
                <li class="nutrient">{{ form.fat.label_tag }}{{ form.fat }}</li>
                <li class="nutrient">{{ form.protein.label_tag }}{{ form.protein }}</li>
                <li class="nutrient">{{ form.salt.label_tag }}{{ form.salt }}</li>
            </ol>
        </fieldset>
        <input class="submit" type="submit" value="Submit"/>
    </form>
</body>

old_version/pantry/templates/health/activity_log_add_old.html
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript">

function change_activity_fields() {
    var act = $("#id_activity").val()
    if (act == "F") {
        $(".food").show()
        $(".ex").hide()
        var prod = $("#id_product").val()
        if (!prod) {
            $("#desc").show()
            $("#prodq").hide()
        } else {
            $("#prodq").show()
            $("#desc").hide()
        }
    } else if (act == "E") {
      $(".ex").show()
      $(".food").hide()
      var ex = $("#id_exercise").val()
      if (!ex) {
            $("#desc").show()
          $("#exmeas").hide()
          $("#exq").hide()     
      } else {
          $("#exmeas").show()
          $("#desc").hide()
          var exmeas = $("#id_exercise_measure").val()
          if (exmeas == "T" || exmeas == 'D' || exmeas =='U') {
              $("#exq").show()
          } else if (exmeas == "E") {
              $("#exq").hide()
          }
      }
    } else {
        alert(value)
    }
}

function set_product_dependents() {
    $.ajax({
        type: "GET",
        url: "/stocks/ajax_get_product/",
        data: {pk: $("#id_product").val()},
        success: function(data) {
            var quant = $("#id_product_quantity").val()
            if (quant) {
                var fields = JSON.parse(data)[0]["fields"]
                if (fields["energy"])
                    $("#id_energy").val(fields["energy"] * quant)
                if (fields["carb"])
                    $("#id_carb").val(fields["carb"] * quant)
                if (fields["fat"]) 
                    $("#id_fat").val(fields["fat"] * quant)
                if (fields["protein"]) 
                    $("#id_protein").val(fields["protein"] * quant)
                if (fields["salt"])
                    $("#id_salt").val(fields["salt"] * quant)
            }
        }
    })
}

function set_exercise_dependents() {
    $.ajax({
        type: "GET",
        url: "/health/ajax_get_exercise/",
        data: {pk: $("#id_exercise").val()},
        success: function(data) {
            var quant = $("#id_exercise_quantity").val()
            if (quant) {
                var fields = JSON.parse(data)[0]["fields"]
                var exmeas = $("#id_exercise_measure").val()
                if (exmeas == "T") {
                    var coeff = fields["energy_time"]
                } else if (exmeas == "D") {
                    var coeff = fields["energy_distance"]
                } else if (exmeas == "U") {
                    var coeff = fields["energy_unit"]
                } else {
                    alert(exmeas)
                }
                $("#id_energy").val((coeff * quant) / 100.0)
            }
        }
    })
}

$(document).ready(change_activity_fields)

$(document).ready(function() {
    $("#id_activity").change(change_activity_fields)
    $("#id_product").change(change_activity_fields)
    $("#id_exercise").change(change_activity_fields)
    $("#id_exercise_measure").change(change_activity_fields)

    $("#id_product_quantity").change(set_product_dependents)
    $("#id_exercise_quantity").change(set_exercise_dependents)
})

</script>
</head>

<body>
    <form action="/health/activity_log/add" method="post">
        {% csrf_token %}
        <p id="user">{{ form.user.label_tag }}: {{ form.user }}</p>
        <p id="date">{{ form.date.label_tag }}: {{ form.date }}</p>

        <p id="activity">{{ form.activity.label_tag }}: {{ form.activity }}</p>

        <p id="prod" class="food">{{ form.product.label_tag }}: {{ form.product }}</p>
        <p id="prodq" class="food">{{ form.product_quantity.label_tag }}: {{ form.product_quantity }}</p>

        <p id="ex" class="ex">{{ form.exercise.label_tag }}: {{ form.exercise }}</p>
        <p id="exmeas" class="ex">{{ form.exercise_measure.label_tag }}: {{ form.exercise_measure }}</p>
        <p id="exq" class="ex">{{ form.exercise_quantity.label_tag }}: {{ form.exercise_quantity }}</p>    

        <p id="energy">{{ form.energy.label_tag }}: {{ form.energy }}</p>
        <p id="carb" class="food">{{ form.carb.label_tag }}: {{ form.carb }}</p>
        <p id="fat" class="food">{{ form.fat.label_tag }}: {{ form.fat }}</p>
        <p id="protein" class="food">{{ form.protein.label_tag }}: {{ form.protein }}</p>
        <p id="salt" class="food">{{ form.salt.label_tag }}: {{ form.salt }}</p>

        <p id="desc">{{ form.description.label_tag }}: {{ form.description }}</p>

        <input type="submit" value="Submit"/>
    </form>
</body>